#!/usr/bin/python

import colorsys

N_CHANNELS = 10

def main():
    delta = 1/(N_CHANNELS)
    hue = 0
    for u in range(N_CHANNELS):
        rgb = colorsys.hsv_to_rgb(hue, 1, 1)
        v = 0
        for c in rgb:
            v = (v << 8) | (255 if c == 1.0 else int(256 * c))
        print(hex(v))
        hue += delta

if __name__ == "__main__":
    main()
